site_name: Lamassu IoT Docs
# Repository
repo_name: Helm Chart
repo_url: https://github.com/lamassuiot/lamassu-helm

theme:
  logo: img/lamassu.svg
  favicon: img/favicon.png
  name: material
  features:
    - navigation.indexes
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: lamassu
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - css/scheme.css
nav:
  - "index.md"
  - Installation:
    - "k8s/1-setup.md"
    - "k8s/2-lamassu-arch.md"
    - 3. Install Infrastructure microservices:
      - "k8s/install-oss-comps.md"
      - "k8s/install-aws-comps.md"
    - "k8s/4-install-lamassu.md"
  - "Get Started":
      - "get-started/admin-pki-setup.md"
      - "get-started/usage-flows.md"
      - "get-started/device-integration.md"
  - "Tech Reference":
    - "tech-ref/architecture.md"
    - "tech-ref/protocols.md"
    - "tech-ref/apis.md"
    - "tech-ref/aws-iot-connector.md"
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lamassuiot
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lamassuiot
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lamassuiot
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
