site_name: Lamassu IoT Docs
# Repository
repo_name: lamassuiot/lamassu-compose
repo_url: https://github.com/lamassuiot/lamassu-compose

theme:
  logo: img/lamassu.svg
  favicon: img/favicon.png
  name: material
  features:
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: lamassu
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - css/scheme.css
nav:
  - "index.md"
  - Installation:
    - "Docker Compose":
      - "docker-compose-setup.md"
      - "Addons":
        - "docker-compose-setup-vtools.md"
        - "docker-compose-setup-aws.md"
      - "docker-compose-manage.md"
    - "Kubernetes":
      - "kubernetes-setup.md"
      - "kubernetes-manage.md"
  - "Get Started":
    - "Provisioning Flows":
      - "usage-flows.md"
      - "usage-flows-first-boot.md"
      - "usage-flows-on-demand.md"
    - "Device Integration":
      - "usage-device-integration.md"
  - "Tech Reference":
    - "architecture.md"
    - "protocols.md"
    - "apis.md"
    - "aws-iot-connector.md"
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lamassuiot
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lamassuiot
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lamassuiot
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
