site_name: Lamassu IoT Docs
theme:
  logo: img/lamassu.svg
  favicon: img/favicon.png
  name: material
  # features:
  #   - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: lamassu
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - css/scheme.css
nav:
  - 'index.md'
  - 'setup.md'
  - 'usage.md'
  - 'protocols.md'
  - 'manage.md'
  - 'extension.md'
  - 'aws.md'
  - 'azure.md'
  - 'jitp.md'
  - 'virtualDMS.md'
  - 'virtualDevice.md'
  - 'pkcs.md'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lamassuiot
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lamassuiot
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lamassuiot
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg