openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Lamassu IoT: VA Service'
  description: |-
    A Validation Authority (VA) is a critical component in a Public Key Infrastructure (PKI), a system that provides secure communication and data exchange over networks. The VA plays a vital role in verifying the validity of digital certificates issued within the PKI framework. It helps ensure the trustworthiness and integrity of the entire PKI ecosystem by acting as a trusted third-party entity.

    This section aims to describe those protocols as well as explaining how to use them.

    Some useful links:
    - [Lamassu IoT Github repository](https://github.com/lamassuiot/lamassuiot)
    - [Lamassu Iot Docs](https://www.lamassu.io/docs/2.5.3/basic-features/va-service/)
    
tags:
  - name: ocsp
  - name: crl
  
paths:
  /ocsp:
    get:
      tags: 
        - ocsp
      summary: Verify OCSP request
      description: Verify OCSP request
      responses:
        200:
          description: Successfully verified OCSP request.
          content:
            application/ocsp-response:
              schema:
                type: string
                format: binary
                description: The OCSP response.
        400:
          description: >
            Bad Request. Possible error reasons:
            - Could not parse and unescape url
            - Could not decode b64 ocsp request
            - Method not supported
            - Could not parse ocsp request
        500:
          description: Something went wrong while verifying ocsp request.
  /ocsp/{ocsp_request}:
    post:
      tags: 
        - ocsp
      summary: Verify OCSP request
      description: Verify OCSP request
      parameters:
        - in: path
          name: ocsp_request
          required: true
          schema:
            type: string
          description: The OCSP request in base64 format.
      requestBody:
        required: true
        content:
          application/ocsp-request:
            schema:
              type: string
              format: binary
              description: The OCSP request in binary format.
      responses:
        200:
          description: Successfully verified OCSP request.
          content:
            application/ocsp-response:
              schema:
                type: string
                format: binary
                description: The OCSP response.
        400:
          description: >
            Bad Request. Possible error reasons:
            - Could not read body
            - Method not supported
            - Could not parse ocsp request
        500:
          description: Something went wrong while verifying ocsp request.
  /crl/{id}:
    get:
      tags: 
        - crl
      summary: Get Certificate Revocation List (CRL) by ID
      description: Get Certificate Revocation List (CRL) by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the Certificate Authority (CA) associated with the CRL.
      responses:
        200:
          description: Successfully retrieved CRL.
          content:
            application/pkix-crl:
              schema:
                type: string
                format: binary
                description: The Certificate Revocation List (CRL) in binary format.
        400:
          description: Bad request. The ID parameter is missing or invalid.
        500:
          description: Something went wrong while verifying ocsp request.
  
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MIKELELOLA003_1/Lamassuiot_VA/1.0.0